version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: apod_postgres
    ports:
      - "5450:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
    volumes:
      - apod_postgres:/var/lib/postgresql/data
    networks:
      - apod

  minio:
    image: minio/minio:RELEASE.2023-02-22T18-23-45Z
    ports:
      - '9000:9000'
      - '9001:9001'
    container_name: apod_minio
    volumes:
      - apod_minio:/data
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key
    command: server --console-address :9001 /data
    networks:
      - apod

  mc:
    image: minio/mc:RELEASE.2023-02-16T19-20-11Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 access_key secret_key;
      /usr/bin/mc mb --quiet local/apod-pictures/;
      /usr/bin/mc anonymous set public local/apod-pictures/;
      "
    networks:
      - apod

  swagger-ui:
    image: swaggerapi/swagger-ui:v4.16.0
    container_name: apod_swaggerui
    ports:
      - "8081:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/v1/picture.yaml
    networks:
      - apod

volumes:
  apod_postgres:
  apod_minio:

networks:
  apod:
    driver: bridge
